language: node_js
node_js: stable
before_deploy:
  - npm run build
sudo: false
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: V54edxa9qWDhk6Xol37u5XsKMgU2CTGbTz9WqF/lqrFQGGj7wOvdaauJygKq9wMo0y2Ki5CTkRM06keNeNZgyJ0gRbdKE43GbiyfehnoNfajmjjEvHN+7UpLgtIpMtCdU0Q6SZg4HY54gMUGozzSiTZek8ODc+atZNLXS9F5XnKIyrtp9O1JbWogWYu7PNe/OCi2xaJvRh4oVnd4CQAp3i7KNkFZlEp7J1kWasJ/zmqTD8Ak+Hz9l8hK3wtC11+07DRSjLmMT3GSExyqyMQ98fvWCe30Qwmp1zB/si9SQNXBU5SvZg9BgTkvRSbGwg62z/TXpaVnWYzWUY0CDon9Y3pl1DBMJlOMG6aFAG0Iv9mN4IoUM5sJhTU+b7KHsGP8UkRpfiSKcAiKC9rk31tSlkVfDfabKRPhWsRGDgKY+P6kl+84oGiZxS5LU5v6aqyVhxrGQYh8sBw0A3n+IJH0Pm6EuZh5j3+0ECw1Nh9Llq5YAvIqvxu9s5Z0G5MLGgAC6vYpGVCI5Y3J69371VTtJWq0f7ROgXDlwCxQ70SRb2QvonqJnKue3WbvlNZe8TKT6RxFdXVSZlbT+ClpuFuvBPf0iaxWB8UQCKVtIL6vFtWWky0XkI4srKUphVrLAdfMHkB192Sk2c7lo4YIn5JTFpOF/oZ9K5sI87g1fbU9w1g=
  app: flagship
  on:
    repo: Wildhoney/Flagship
